# Release a new TW Blue installer on github.
# This workflow runs on push.
name: AutoBuild
on:
  push:
    branches:
      - "yt-dlp"

jobs:
  build:
  # Builds an x64 binary and an installer of TW Blue.
    runs-on: windows-2025
    steps:
    - name: clone repo
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Get python interpreter
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        cache: 'pip'
    - name: Install python packages
      run: pip install --upgrade pip -r requirements.txt
    - name: Build binary
      run: .\scripts\build_pyinstaller.ps1
    - name: uploadArtifact
      uses: actions/upload-artifact@v4
      with:
        name: twblue_binary
        path: ./src/dist/TWBlue
        retention-days: 3
