# Release a new TW Blue installer on github.
# This workflow runs on push.
name: AutoBuild
on:
  push:
    branches:
      - "yt-dlp"
env:
  PYTHON_VERSION: "3.14"
jobs:
  build:
  # Builds an x64 binary and an installer of TW Blue.
    runs-on: windows-2025
    steps:
    - name: clone repo
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Build binary
      run: .\scripts\build_pyinstaller.ps1
    - name: uploadArtifact
      uses: actions/upload-artifact@v4
      with:
        name: twblue_binary
        path: ./src/dist/TWBlue
        retention-days: 3
